config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'places#index'
  resources :places do
    resources :comments, only: :create  
    resources :users, :only => :show
      end
  resources :places do
    resources :photos, only: :create
    resources :users, :only => :show
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :place


  RATINGS = {
    'one star': '1_star',
    'two stars': '2_stars',
    'three stars': '3_stars',
    'four stars': '4_stars',
    'five stars': '5_stars'
  }

  def humanized_rating
    RATINGS.invert[self.rating]
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
  belongs_to :place
  has_many :comments
  has_many :photos


  geocoded_by :address
  after_validation :geocode

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :place
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :places
  has_many :comments
  has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @place = Place.find(params[:place_id])
    @place.comments.create(comment_params.merge(user: current_user))
    redirect_to place_path(@place)
  end


  private

  def comment_params
    params.require(:comment).permit(:message, :rating)
  end
end

app/controllers/concerns/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!

  def create
    @photos = Place.find(params[:place_id])
    @place.photos.create(photos_params.merge(user: current_user))
    redirect_to place_path(@place)
  end


  private

  def photos_params
    params.require(:photos).permit(:caption)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!


  def create
    @place = Place.find(params[:place_id])
    @place.photos.create(photo_params.merge(user: current_user))
    redirect_to place_path(@place)
  end

  private

  def photo_params
    params.require(:photo).permit(:caption, :picture)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @places = Place.all
  end

  def new
    @place = Place.new
  end

  def create
    @place = current_user.places.create(place_params)
    if @place.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @place = Place.find(params[:id])
    @comment = Comment.new
    @photo = Photo.new
  end

  def edit
    @place = Place.find(params[:id])


  if @place.user != current_user
    return render plain: 'Not Allowed', status: :forbidden
  end
  end

  def update
    @place = Place.find(params[:id])

    if @place.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end


    @place.update_attributes(place_params)
    if @place.valid?
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @place = Place.find(params[:id])
    if @place.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end

    @place.destroy
    redirect_to root_path
  end

  private

  def place_params
    params.require(:place).permit(:name, :description, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nomster</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>


    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <%= link_to 'Nomster', root_path, class: 'navbar-brand' %>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item active">
           
            <%= link_to new_place_path, class: 'nav-link' do %>
              <i class="fa fa-plus-circle"></i>
              New Place
            <% end %>
           </li>
         </ul>
         <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>

      </div>
    </nav>

    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>


  </body>
</html>

app/views/places/edit.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Edit Your Place</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Update', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/places/index.html.erb
<% @places.each do |place| %>
  <div class="booyah-box col-10 offset-1">
    <h1><%= link_to place.name, place_path(place) %></h1><br />
    <i><%= place.address %></i><br /><br />
    <p><%= place.description %></p><br />


    <% if place.user.present? %>
      <small><%= place.user.email %></small>
    <% end %>

  <%if place.comments.present? %>
    <div class="col-12">
      <blockquote>
        <% if place.comments.last.humanized_rating.present? %>
          <b><%= place.comments.last.humanized_rating %></b> -
        <% end %>
        <%= place.comments.last.message %>
        <small><%= place.comments.last.user.email %></small>
      </blockquote>
    </div>
  <% end %>
    
  <% if place.photos.present? %>
   <div class="col-12">
        <blockquote>
          <% if place.photos.last.humanized_caption.present? %>
            <b><%= place.photos.last.humanized_caption %></b> -
          <% end %>
          <%= place.photos.last.picture %>
          <small><%= place.photos.last.user.email %></small>
        </blockquote>
   </div>
  <% end %> 


  </div>
<% end %>

app/views/places/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Enter Your Place Details</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/places/show.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1><%= @place.name %></h1>
  <br /><br />
  <i><%= @place.address %></i>
  <p><%= @place.description %></p>
  
  <% if @place.latitude.present? && @place.longitude.present? %>

  <script>

    function initMap() {
      var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};

      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 12,
        center: myLatLng
      });

      var marker = new google.maps.Marker({
        position: myLatLng,
        map: map,
        title: 'Hello World!'
      });
    }
  </script>

  <script asinc defer
  src="https//maps.googleapis.com/maps/api/js?key=AIzaSyA6s2gS_Gia7tUgk23dhsOkxPMVjZhjwvg&callback=initMap">
  </script>
  <br />
  <div id="map"></div>
  
  <% end %>
  <br />
  
  <div class="float-right">
    <% if current_user && current_user == @place.user %>
      <%= link_to 'Edit', edit_place_path(@place), class: 'btn btn-primary' %>
      <%= link_to 'Destroy', place_path(@place), method: :delete, data: {confirm: 'Are you sure you want to delete this?'}, class: 'btn btn-danger' %>
    <% end %>
  </div>

  <br />
  <br />
</div>

<div class ='clear'></div>
<%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
  <%= f.input :message %>
  <%= f.input :rating, as: :select, collection: Comment::RATINGS %>

  <%= f.submit "Add a Comment", class: 'btn btn-primary' %>
<% end %>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Add a Comment</h4>
      </div>
      <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
        <div class="modal-body">
          <%= f.input :message %>
          <%= f.input :rating, as: :select, collection: Comment::RATINGS %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "Add a Comment", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>


<div class="col-10 offset-1">
  <h1 class="float-left">Comments</h1>
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary btn-lg float-right" data-toggle="modal" data-target="#myModal">
    Add a comment
  </button>
</div>


<div class='clear'></div>

<h1>Comments</h1>

<div class="row">
  <% @place.comments.each do |comment| %>
    <div class="col-12 col-sm-6">
      <blockquote>
        <% if comment.humanized_rating.present? %>
         <b><%= comment.humanized_rating %></b> -
        <% end %>
        <%= comment.message %>
        <small><%= comment.user.email %></small>
      </blockquote>
    </div>
  <% end %>

  
<div class ="clear"></div> 
<% simple_form_for @photo, url: place_photos_path(@place) do |f| %>
  <%= f.input :caption %>
  <%= f.input :picture %>
  <%= f.submit "Add a Photo", class: 'btn btn-primary' %>
<% end %>

<h1>Photos</h1>

<div class="row">
  <% @place.photos.each do |photo| %>
    <div class="col-12 col-sm-6">
      <blockquote>
        <% if photo.humanized_caption.present? %>
          <b><%= photo.humanized_caption %></b> -
        <% end %>
        <%= photo.caption %>
        <%= photo.picture %>
        <small><%= photo.user.email %></small>
      </blockquote>
   </div>
  <% end %>
</div>


<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Add a Photo
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Add a Photo</h4>
      </div>   
      <% simple_form_for @photo, url: place_photos_path(@place) do |f| %>
        <div class="modal-body">
          <%= f.input :caption %>
          <%= f.input :picture %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "Add a Photo", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>


<div class="col-10 offset-1">  <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary btn-lg float-right" data-toggle="modal" data-target="#myModal">
  Add a Photo
  </button>
</div>


<div class="clear"></div>